version: "3"

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ../data:/var/lib/mysql
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
#  nginx:
#    image: nginx
#    container_name: nginx_reverse_proxy
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./generate_tls.sh:/generate_tls.sh
#    depends_on:
#      - web_app
#    command: ["/bin/bash", "/generate_tls.sh"]
