version: "3"

services:

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
    depends_on:
      - fluentd
    restart: always
    volumes:
      - ../data:/var/lib/mysql
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
    networks:
      - le_pond

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ../images:/app/static/images
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
    networks:
      - le_pond

  web_app_backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app_backup
    ports:
      - "5001:5000"
    restart: always
    volumes:
      - ../images_backup:/app/static/images
    networks:
      - le_pond

  fluentd:
    build: monitoring/fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
    networks:
      - le_pond

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - le_pond

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - le_pond

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - le_pond

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - "--port=8445"
    ports:
      - "8445:8445"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - web_app
    networks:
      - le_pond

networks:
  le_pond:
    external: true