version: "3"

services:

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ../data:/var/lib/mysql

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ../images:/app/static/images

  web_app_backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app_backup
    ports:
      - "5001:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ../images:/app/static/images