version: "3"

services:

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
    depends_on:
      - fluentd
    restart: always
    volumes:
      - ../data:/var/lib/mysql
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
    networks:
      - le_pond

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ../images:/app/static/images
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
    networks:
      - le_pond

  web_app_backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app_backup
    ports:
      - "5001:5000"
    restart: always
    volumes:
      - ../images_backup:/app/static/images
    networks:
      - le_pond

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
    networks:
      - le_pond

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - le_pond

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - le_pond

networks:
  le_pond:
    external: true