version: "3"

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database