version: "3"

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_app
