on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download dependencies
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Install dependencies
        run: sudo chmod +x /usr/local/bin/docker-compose
      - name: Deploy web app
        run: docker-compose up -d
      - name: Check container ip
        run: docker inspect web_app
      - name: Check state of web app
        run: curl http://web_app:5000