name: CI deployment to production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy webapp on EC2 Instance
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.EC2_SSH_HOST }}
          username: ${{ vars.EC2_SSH_USER }}
          key: ${{ vars.EC2_SSH_KEY }}
          port: ${{ vars.EC2_SSH_PORT }}
          envs: GITHUB_HEAD_REF
          script: |
            cd /mnt/data
            cd devops-journey
            sudo git restore .
            sudo git pull
            sudo chmod u+x ./deployment.sh
            sudo ./deployment.sh
      - name: Sanity check on ec3
        run: curl -s -o /dev/null -w "%{http_code}" https://blog.vizallati.guru/categories?category=aqa | grep -q "^200$" || exit 1
