name: CI deployment to test env

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download dependencies
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Install dependencies
        run: sudo chmod +x /usr/local/bin/docker-compose
      - name: Deploy webapp on runner node
        run: docker-compose up -d
      - name: Expose port used by web app
        run: sudo ufw allow 5000
      - name: Wait for server to be fully initialized on runner node
        run: sleep 30
      - name: Sanity check on runner node
        run: curl localhost:5000